spring:
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost/monitoring
    username: app
    password: appPassword



monitoring:
  services:
    -
      name: "service1"
      healthUrl: "https://mock.codes/200"
    -
      name: "service2"
      healthUrl: "https://mock.codes/500"